%?BetterClub ?Club
is_better(Club1, Club2):-
    is_higher(Club1, Club3),
    is_better(Club3, Club2).

is_better(Club1, Club2):-
    is_higher(Club1, Club2).

%?HihgerClub ?LowerClub
is_higher(realMadrid, bayernMunchen).
is_higher(bayernMunchen, fCBarcelona).
is_higher(fCBarcelona, atleticoMadrid).
is_higher(atleticoMadrid, juventus).
is_higher(juventus, parisSaintGermain).
is_higher(parisSaintGermain, borussiaDortmund).
is_higher(borussiaDortmund, sevilla).
is_higher(sevilla, benfica).
is_higher(benfica, chelsea).
is_higher(chelsea, arsenal).
is_higher(arsenal, manchesterCity).
is_higher(manchesterCity, fCPorto).
is_higher(fCPorto, schalke04).
is_higher(schalke04, bayerLeverkusen).
is_higher(bayerLeverkusen, napoli).
is_higher(napoli, shakhtarDonetsk).
is_higher(shakhtarDonetsk, zenitStPetersburg).
is_higher(zenitStPetersburg, manchesterUnited).
is_higher(manchesterUnited, tottenhamHotspur).
is_higher(tottenhamHotspur, valencia).
is_higher(valencia, fCBasel).
is_higher(fCBasel, fiorentina).
is_higher(fiorentina, dinamoKiev).
is_higher(dinamoKiev, olympiakosPiraeus).
is_higher(olympiakosPiraeus, villarreal).
is_higher(villarreal, olympiqueLyon).
is_higher(olympiqueLyon, athleticBilbao).
is_higher(athleticBilbao, galatasaray).
is_higher(galatasaray, ajax).
is_higher(ajax, aSMonaco).
is_higher(aSMonaco, lazio).
is_higher(lazio, liverpool).
is_higher(liverpool, vfLWolfsburg).
is_higher(vfLWolfsburg, anderlecht).
is_higher(anderlecht, dniproDnipropetrovsk).
is_higher(dniproDnipropetrovsk, borussiaMonchengladbach).
is_higher(borussiaMonchengladbach, fenerbahce).
is_higher(fenerbahce, aSRoma).
is_higher(aSRoma, spartaPraha).
is_higher(spartaPraha, aCMilan).
is_higher(aCMilan, pSVEindhoven).
is_higher(pSVEindhoven, internazionale).
is_higher(internazionale, rubinKazan).
is_higher(rubinKazan, celtic).
is_higher(celtic, malagaCF).
is_higher(malagaCF, racingGenk).
is_higher(racingGenk, besiktas).
is_higher(besiktas, viktoriaPlzen).
is_higher(viktoriaPlzen, fCSalzburg).
is_higher(fCSalzburg, cSKAMoscow).
is_higher(cSKAMoscow, clubBrugge).
is_higher(clubBrugge, fCKobenhavn).
is_higher(fCKobenhavn, sportingBraga).
is_higher(sportingBraga, sportingCPLisbon).
is_higher(sportingCPLisbon, leicesterCity).
is_higher(leicesterCity, aSSaintEtienne).
is_higher(aSSaintEtienne, steauaBucuresti).
is_higher(steauaBucuresti, pAOKThessaloniki).
is_higher(pAOKThessaloniki, ludogoretsRazgrad).
is_higher(ludogoretsRazgrad, aAGent).
is_higher(aAGent, levanteUD).
is_higher(levanteUD, aZAlkmaar).
is_higher(aZAlkmaar, realBetis).
is_higher(realBetis, fKKrasnodar).
is_higher(fKKrasnodar, celtadeVigo).
is_higher(celtadeVigo, anzhiMakhachkala).
is_higher(anzhiMakhachkala, newcastleUnited).
is_higher(newcastleUnited, bATEBorisov).
is_higher(bATEBorisov, girondinsBordeaux).
is_higher(girondinsBordeaux, youngBoys).
is_higher(youngBoys, everton).
is_higher(everton, rapidWien).
is_higher(rapidWien, legiaWarsaw).
is_higher(legiaWarsaw, olympiqueMarseille).
is_higher(olympiqueMarseille, eintrachtFrankfurt).
is_higher(eintrachtFrankfurt, dinamoMoscow).
is_higher(dinamoMoscow, torino).
is_higher(torino, trabzonspor).
is_higher(trabzonspor, realSociedad).
is_higher(realSociedad, vfBStuttgart).
is_higher(vfBStuttgart, aPOELNicosia).
is_higher(aPOELNicosia, dinamoZagreb).
is_higher(dinamoZagreb, hannover96).
is_higher(hannover96, slovanLiberec).
is_higher(slovanLiberec, fSVMainz05).
is_higher(fSVMainz05, fKRostov).
is_higher(fKRostov, maccabiTelAviv).
is_higher(maccabiTelAviv, feyenoord).
is_higher(feyenoord, fCAugsburg).
is_higher(fCAugsburg, southamptonFC).
is_higher(southamptonFC, lilleOSC).
is_higher(lilleOSC, swanseaCity).
is_higher(swanseaCity, nKMaribor).
is_higher(nKMaribor, sCFreiburg).
is_higher(sCFreiburg, standardLiege).
is_higher(standardLiege, lokomotivMoscow).
is_higher(lokomotivMoscow, metalistKharkiv).
is_higher(metalistKharkiv, moldeFK).
is_higher(moldeFK, enAvantGuingamp).
is_higher(enAvantGuingamp, udinese).
is_higher(udinese, wiganAthletic).
is_higher(wiganAthletic, spartakMoscow).
is_higher(spartakMoscow, fCZurich).
is_higher(fCZurich, sassuolo).
is_higher(sassuolo, garabagAgdam).
is_higher(garabagAgdam, astraGiurgiu).
is_higher(astraGiurgiu, chernomoretsOdesa).
is_higher(chernomoretsOdesa, westHamUnited).
is_higher(westHamUnited, austriaWien).
is_higher(austriaWien, montpellier).
is_higher(montpellier, malmoFF).
is_higher(malmoFF, cFRCluj).
is_higher(cFRCluj, estorilPraia).
is_higher(estorilPraia, fKAstana).
is_higher(fKAstana, herthaBSC).
is_higher(herthaBSC, kSCLokeren).
is_higher(kSCLokeren, oGCNice).
is_higher(oGCNice, fCMidtjylland).
is_higher(fCMidtjylland, hullCity).
is_higher(hullCity, partizanBelgrade).
is_higher(partizanBelgrade, osmanlispor).
is_higher(osmanlispor, asterasTripolis).
is_higher(asterasTripolis, nKRijeka).
is_higher(nKRijeka, sampdoria).
is_higher(sampdoria, kubanKrasnodar).
is_higher(kubanKrasnodar, panathinaikos).
is_higher(panathinaikos, vitoriaGuimaraes).
is_higher(vitoriaGuimaraes, maritimoFunchal).
is_higher(maritimoFunchal, esbjergfB).
is_higher(esbjergfB, fCSion).
is_higher(fCSion, zulteWaregem).
is_higher(zulteWaregem, rioAve).
is_higher(rioAve, cFOsBelenenses).
is_higher(cFOsBelenenses, academicaCoimbra).
is_higher(academicaCoimbra, zoryaLuhansk).
is_higher(zoryaLuhansk, pacosdeFerreira).
is_higher(pacosdeFerreira, rosenborgBK).
is_higher(rosenborgBK, hajdukSplit).
is_higher(hajdukSplit, fCArouca).
is_higher(fCArouca, nacionalFunchal).
is_higher(nacionalFunchal, fCTwenteEnschede).
is_higher(fCTwenteEnschede, aaBAalborg).
is_higher(aaBAalborg, fCNordsjalland).
is_higher(fCNordsjalland, sheriffTiraspol).
is_higher(sheriffTiraspol, atromitosFC).
is_higher(atromitosFC, dinamoMinsk).
is_higher(dinamoMinsk, lechPoznan).
is_higher(lechPoznan, grasshoppersZurich).
is_higher(grasshoppersZurich, hapoelBeerSheva).
is_higher(hapoelBeerSheva, apollonLimassol).
is_higher(apollonLimassol, bursaspor).
is_higher(bursaspor, hJKHelsinki).
is_higher(hJKHelsinki, vorsklaPoltava).
is_higher(vorsklaPoltava, metalurgDonetsk).
is_higher(metalurgDonetsk, iFElfsborg).
is_higher(iFElfsborg, fCSanktGallen).
is_higher(fCSanktGallen, istanbulBasaksehir).
is_higher(istanbulBasaksehir, mladaBoleslav).
is_higher(mladaBoleslav, aIKStockholm).
is_higher(aIKStockholm, fCThun).
is_higher(fCThun, neftchiBaku).
is_higher(neftchiBaku, konyaspor).
is_higher(konyaspor, fKJablonec).
is_higher(fKJablonec, fCOleksandriya).
is_higher(fCOleksandriya, arsenalKiev).
is_higher(arsenalKiev, fCLuzern).
is_higher(fCLuzern, charleroi).
is_higher(charleroi, karabukspor).
is_higher(karabukspor, vojvodinaNoviSad).
is_higher(vojvodinaNoviSad, vitesseArnhem).
is_higher(vitesseArnhem, brondbyIF).
is_higher(brondbyIF, videotonFehervar).
is_higher(videotonFehervar, eskisehirspor).
is_higher(eskisehirspor, maccabiHaifa).
is_higher(maccabiHaifa, hapoelTelAviv).
is_higher(hapoelTelAviv, fCGroningen).
is_higher(fCGroningen, omoniaNicosia).
is_higher(omoniaNicosia, aELLimassol).
is_higher(aELLimassol, slaviaPraha).
is_higher(slaviaPraha, iFKGoteborg).
is_higher(iFKGoteborg, hapoelKiryatShmona).
is_higher(hapoelKiryatShmona, panduriiTarguJiu).
is_higher(panduriiTarguJiu, petrolulPloiesti).
is_higher(petrolulPloiesti, gabalaFK).
is_higher(gabalaFK, tromsoIL).
is_higher(tromsoIL, lokomotivaZagreb).
is_higher(lokomotivaZagreb, fKAktobe).
is_higher(fKAktobe, shakhtiorSaligorsk).
is_higher(shakhtiorSaligorsk, slaskWroclaw).
is_higher(slaskWroclaw, servetteFCGeneve).
is_higher(servetteFCGeneve, pECZwolle).
is_higher(pECZwolle, heerenveen).
is_higher(heerenveen, slovanBratislava).
is_higher(slovanBratislava, redStarBelgrade).
is_higher(redStarBelgrade, stromsgodsetIF).
is_higher(stromsgodsetIF, admiraWacker).
is_higher(admiraWacker, shakhtyorKaraganda).
is_higher(shakhtyorKaraganda, helsingborgIF).
is_higher(helsingborgIF, dVSCDebrecen).
is_higher(dVSCDebrecen, heraclesAlmelo).
is_higher(heraclesAlmelo, aSTrencin).
is_higher(aSTrencin, spartakTrnava).
is_higher(spartakTrnava, skenderbeuKorce).
is_higher(skenderbeuKorce, aberdeen).
is_higher(aberdeen, motherwell).
is_higher(motherwell, pASGiannina).
is_higher(pASGiannina, aEKAthens).
is_higher(aEKAthens, xanthiFC).
is_higher(xanthiFC, sCRAltach).
is_higher(sCRAltach, sturmGraz).
is_higher(sturmGraz, fCPasching).
is_higher(fCPasching, rNKSplit).
is_higher(rNKSplit, stJohnstone).
is_higher(stJohnstone, ruchChorzow).
is_higher(ruchChorzow, dinamoBucuresti).
is_higher(dinamoBucuresti, fCVaslui).
is_higher(fCVaslui, fCUtrecht).
is_higher(fCUtrecht, sonderjyskE).
is_higher(sonderjyskE, randersFC).
is_higher(randersFC, aCHorsens).
is_higher(aCHorsens, aEKLarnaca).
is_higher(aEKLarnaca, fHHafnarfjardar).
is_higher(fHHafnarfjardar, goAheadEagles).
is_higher(goAheadEagles, wolfsbergerAC).
is_higher(wolfsbergerAC, sVGrodig).
is_higher(sVGrodig, stPolten).
is_higher(stPolten, sVRied).
is_higher(sVRied, slavenKoprivnica).
is_higher(slavenKoprivnica, interBaku).
is_higher(interBaku, beitarJerusalem).
is_higher(beitarJerusalem, viitorulConstanta).
is_higher(viitorulConstanta, aSATirguMures).
is_higher(aSATirguMures, rapidBucuresti).
is_higher(rapidBucuresti, mSKZilina).
is_higher(mSKZilina, zalgirisVilnius).
is_higher(zalgirisVilnius, dundalk).
is_higher(dundalk, heartsFC).
is_higher(heartsFC, theNewSaints).
is_higher(theNewSaints, fKVentspils).
is_higher(fKVentspils, oddGrenland).
is_higher(oddGrenland, kairatAlmaty).
is_higher(kairatAlmaty, nKOsijek).
is_higher(nKOsijek, dinamoTbilisi).
is_higher(dinamoTbilisi, dilaGori).
is_higher(dilaGori, fKMinsk).
is_higher(fKMinsk, bKHacken).
is_higher(bKHacken, cSMSIasi).
is_higher(cSMSIasi, fCBotosani).
is_higher(fCBotosani, aGFAarhus).
is_higher(aGFAarhus, fKSarajevo).
is_higher(fKSarajevo, torpedoZhodino).
is_higher(torpedoZhodino, anorthosisFamagusta).
is_higher(anorthosisFamagusta, kRReykjavik).
is_higher(kRReykjavik, vardarSkopje).
is_higher(vardarSkopje, f91Dudelange).
is_higher(f91Dudelange, fCGomel).
is_higher(fCGomel, zaglebieLubin).
is_higher(zaglebieLubin, piastGliwice).
is_higher(piastGliwice, iFKNorrkoping).
is_higher(iFKNorrkoping, iFBrommapojkarna).
is_higher(iFBrommapojkarna, gefleIF).
is_higher(gefleIF, kalmarFF).
is_higher(kalmarFF, milsamiOrhei).
is_higher(milsamiOrhei, hapoelRamatGan).
is_higher(hapoelRamatGan, bneiYehuda).
is_higher(bneiYehuda, kaljuNomme).
is_higher(kaljuNomme, zeljeznicarSarajevo).
is_higher(zeljeznicarSarajevo, hibernian).
is_higher(hibernian, dundeeUnited).
is_higher(dundeeUnited, ermisAradippou).
is_higher(ermisAradippou, fCBeroeStaraZagora).
is_higher(fCBeroeStaraZagora, botevPlovdiv).
is_higher(botevPlovdiv, aalesundsFK).
is_higher(aalesundsFK, olimpijaLjubljana).
is_higher(olimpijaLjubljana, cukarickiBelgrade).
is_higher(cukarickiBelgrade, vallettaFC).
is_higher(vallettaFC, khazarLenkoran).
is_higher(khazarLenkoran, fKKukesi).
is_higher(fKKukesi, nemanGrodno).
is_higher(nemanGrodno, naftanNovopolotsk).
is_higher(naftanNovopolotsk, fCVaduz).
is_higher(fCVaduz, jagielloniaBialystok).
is_higher(jagielloniaBialystok, zawiszaBydgoszcz).
is_higher(zawiszaBydgoszcz, levskiSofia).
is_higher(levskiSofia, zimbruChisinau).
is_higher(zimbruChisinau, maccabiNetanya).
is_higher(maccabiNetanya, fKJagodina).
is_higher(fKJagodina, stPatricksAthletic).
is_higher(stPatricksAthletic, invernessCT).
is_higher(invernessCT, cracoviaKrakow).
is_higher(cracoviaKrakow, cSKASofia).
is_higher(cSKASofia, stjarnanFC).
is_higher(stjarnanFC, stabakIF).
is_higher(stabakIF, fKHaugesund).
is_higher(fKHaugesund, iLHodd).
is_higher(iLHodd, nKDomzale).
is_higher(nKDomzale, muraMurskaSobota).
is_higher(muraMurskaSobota, kapazGanja).
is_higher(kapazGanja, zrinjskiMostar).
is_higher(zrinjskiMostar, ordabasyShymkent).
is_higher(ordabasyShymkent, levadiaTallinn).
is_higher(levadiaTallinn, litexLovech).
is_higher(litexLovech, ferencvaros).
is_higher(ferencvaros, crusadersBelfast).
is_higher(crusadersBelfast, rabotnickiSkopje).
is_higher(rabotnickiSkopje, birkirkara).
is_higher(birkirkara, fKBaku).
is_higher(fKBaku, shirakGyumri).
is_higher(shirakGyumri, chernoMoreVarna).
is_higher(chernoMoreVarna, lokomotivPlovdiv).
is_higher(lokomotivPlovdiv, cliftonville).
is_higher(cliftonville, daciaChisinau).
is_higher(daciaChisinau, linfieldBelfast).
is_higher(linfieldBelfast, nKKoper).
is_higher(nKKoper, ekranasPanevezys).
is_higher(ekranasPanevezys, mladostPodgorica).
is_higher(mladostPodgorica, irtyshPavlodar).
is_higher(irtyshPavlodar, sirokiBrijeg).
is_higher(sirokiBrijeg, cSFolaEsch).
is_higher(cSFolaEsch, differdange03).
is_higher(differdange03, slaviaSofia).
is_higher(slaviaSofia, eTOGyor).
is_higher(eTOGyor, shkendijaTetovo).
is_higher(shkendijaTetovo, novaGorica).
is_higher(novaGorica, nKCelje).
is_higher(nKCelje, fKSenica).
is_higher(fKSenica, sligoRovers).
is_higher(sligoRovers, buducnostPodgorica).
is_higher(buducnostPodgorica, zhetysuTaldykorgan).
is_higher(zhetysuTaldykorgan, sutjeskaNiksic).
is_higher(sutjeskaNiksic, pyunikYerevan).
is_higher(pyunikYerevan, shamrockRovers).
is_higher(shamrockRovers, partizaniTirana).
is_higher(partizaniTirana, floraTallinn).
is_higher(floraTallinn, rudarPljevlja).
is_higher(rudarPljevlja, chikhuraSachkhere).
is_higher(chikhuraSachkhere, lincolnRedImps).
is_higher(lincolnRedImps, fKJelgava).
is_higher(fKJelgava, vikingur).
is_higher(vikingur, breidablik).
is_higher(breidablik, mTKBudapest).
is_higher(mTKBudapest, diosgyoriMiskolc).
is_higher(diosgyoriMiskolc, honvedBudapest).
is_higher(honvedBudapest, rudarVelenje).
is_higher(rudarVelenje, metalurgSkopje).
is_higher(metalurgSkopje, mFKKosice).
is_higher(mFKKosice, hiberniansFC).
is_higher(hiberniansFC, sJKSeinajoki).
is_higher(sJKSeinajoki, fCZestafoni).
is_higher(fCZestafoni, fCSantaColoma).
is_higher(fCSantaColoma, skontoRiga).
is_higher(skontoRiga, daugavaDaugavpils).
is_higher(daugavaDaugavpils, spartakMyjava).
is_higher(spartakMyjava, corkCity).
is_higher(corkCity, zetaGolubovci).
is_higher(zetaGolubovci, roPSRovaniemi).
is_higher(roPSRovaniemi, myPa47).
is_higher(myPa47, kuPSKuopio).
is_higher(kuPSKuopio, alashkertFC).
is_higher(alashkertFC, b36Torshavn).
is_higher(b36Torshavn, uSVEschenMauren).
is_higher(uSVEschenMauren, hBTorshavn).
is_higher(hBTorshavn, iBVVestmannaeyjar).
is_higher(iBVVestmannaeyjar, fCTiraspol).
is_higher(fCTiraspol, derryCity).
is_higher(derryCity, kFLaci).
is_higher(kFLaci, honkaEspoo).
is_higher(honkaEspoo, interTurku).
is_higher(interTurku, ulissesYerevan).
is_higher(ulissesYerevan, fKLiepaja).
is_higher(fKLiepaja, jeunessedEsch).
is_higher(jeunessedEsch, thorAkureyri).
is_higher(thorAkureyri, zariaBalti).
is_higher(zariaBalti, saxanGagauzYeri).
is_higher(saxanGagauzYeri, verisChisinau).
is_higher(verisChisinau, teutaDurres).
is_higher(teutaDurres, celikNiksic).
is_higher(celikNiksic, kSFlamurtariVlore).
is_higher(kSFlamurtariVlore, iFKMariehamn).
is_higher(iFKMariehamn, vPSVaasa).
is_higher(vPSVaasa, jJKJyvaskyla).
is_higher(jJKJyvaskyla, spartaksJurmala).
is_higher(spartaksJurmala, metalurgsLiepaja).
is_higher(metalurgsLiepaja, eBStreymur).
is_higher(eBStreymur, valurReykjavik).
is_higher(valurReykjavik, vikingurReykjavik).
is_higher(vikingurReykjavik, framReykjavik).
is_higher(framReykjavik, renovaDzepciste).
is_higher(renovaDzepciste, fKTurnovo).
is_higher(fKTurnovo, atlantasKlaipeda).
is_higher(atlantasKlaipeda, suduvaMarijampole).
is_higher(suduvaMarijampole, uniCollegeDublin).
is_higher(uniCollegeDublin, kalevSillamae).
is_higher(kalevSillamae, sKTirana).
is_higher(sKTirana, fCLahti).
is_higher(fCLahti, tPSTurku).
is_higher(tPSTurku, banantsYerevan).
is_higher(banantsYerevan, gandzasarKapan).
is_higher(gandzasarKapan, torpedoKutaisi).
is_higher(torpedoKutaisi, olimpiRustavi).
is_higher(olimpiRustavi, fCLusitanos).
is_higher(fCLusitanos, glenavon).
is_higher(glenavon, fKTrakai).
is_higher(fKTrakai, trePenne).
is_higher(trePenne, laFiorita).
is_higher(laFiorita, droghedaUnited).
is_higher(droghedaUnited, bohemiansDublin).
is_higher(bohemiansDublin, slobodaTuzla).
is_higher(slobodaTuzla, radnikBijeljina).
is_higher(radnikBijeljina, transNarva).
is_higher(transNarva, olimpicSarajevo).
is_higher(olimpicSarajevo, fKBoracBanjaLuka).
is_higher(fKBoracBanjaLuka, samtredia).
is_higher(samtredia, balaTown).
is_higher(balaTown, dinamoBatumi).
is_higher(dinamoBatumi, spartakTskhinvali).
is_higher(spartakTskhinvali, mikaAshtarak).
is_higher(mikaAshtarak, sioniBolnisi).
is_higher(sioniBolnisi, airbusUKBroughton).
is_higher(airbusUKBroughton, europaFC).
is_higher(europaFC, daugavaRiga).
is_higher(daugavaRiga, nSIRunavik).
is_higher(nSIRunavik, glentoran).
is_higher(glentoran, portadown).
is_higher(portadown, sileksKratovo).
is_higher(sileksKratovo, teteksTetovo).
is_higher(teteksTetovo, kruojaPakruojis).
is_higher(kruojaPakruojis, infonetTallinn).
is_higher(infonetTallinn, balzanFC).
is_higher(balzanFC, bokeljKotor).
is_higher(bokeljKotor, santosTartu).
is_higher(santosTartu, sliemaWanderers).
is_higher(sliemaWanderers, lovcenCetinje).
is_higher(lovcenCetinje, connahsQuay).
is_higher(connahsQuay, newtown).
is_higher(newtown, bangorCity).
is_higher(bangorCity, prestatynTown).
is_higher(prestatynTown, uESantaColoma).
is_higher(uESantaColoma, progresNiederkorn).
is_higher(progresNiederkorn, cSGrevenmacher).
is_higher(cSGrevenmacher, iFFuglafjordur).
is_higher(iFFuglafjordur, bangaGargzdai).
is_higher(bangaGargzdai, fKSiauliai).
is_higher(fKSiauliai, folgore).
is_higher(folgore, floriana).
is_higher(floriana, llandudnoFC).
is_higher(llandudnoFC, aberystwythTown).
is_higher(aberystwythTown, cefnDruids).
is_higher(cefnDruids, llanelliFC).
is_higher(llanelliFC, libertas).
is_higher(libertas, santJulia).
is_higher(santJulia, juvenesDogana).